quotearray = ['...it\'s a new feature. Don\'t tell anyone it was an accident — Larry Wall',
'One man\'s crappy software is another man\'s job - Alan Perlis',
'Programming is like sex. One mistake and you have to support it for the rest of your life — Michael Sinz',
'There are two ways to write error-free programs; only the third one works. — Alan J. Perlis',
'The only thing more expensive than writing software is writing bad software. — Anonymous',
'The best thing about a boolean is even if you are wrong, you are only off by a bit. — Anonymous',
'Quality is not an act, it is a habit - Aristotle',
'Any decent tester has the heart of a developer... in a jar on their desk - Anonymous',
'It\'s not working as intended, but it is working as coded - Anonymous',
'The most dangerous phrase in the language is, We\'ve always done it this way — Grace Hopper',
'Programming isn\'t about what you know; it\'s about what you can figure out — Chris Pine',
'Code is like humor. When you have to explain it, it\'s bad. — Cory House',
'The best error message is the one that never shows up. — Anonymous',
'Programmers never die; they just go offline — Anonymous',
'Programming is the art of telling a computer what to do — Anonymous']
@randquote = quotearray[rand(quotearray.length)]